version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Ninja@13
      MYSQL_DATABASE: security_demo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Ninja@13
    ports:
      - "8081:80"
    depends_on:
      - mysql

  spring-app:
    image: vivek010/spring-security-img-springboot:latest
    container_name: spring_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/security_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ninja@13
      SERVER_PORT: 8000
    restart: on-failure

volumes:
  mysql_data:
